### ISSUE TITLE
Exiting before completing 

### ISSUE THREAD

**Issue by pedmondson1** [tamhinsf/ChannelSurf#15]
I've run into a problem with this tool. I am able to run the program and connect to my azure tenant. However, when it gets to line 121's in program.cs it uses' Environment.Exit variable which im assuming is due to having a blank selectedTeamID. 

I am wondering where i might have gone wrong to miss this variable. 

I've run both commands 
* dotnet run /path/to/channels.json
* dotnet run /path/to/slack/archive/myexport.zip (replace myexport.zip with your archive filename)

Both lead to the same result. 

i am able to complete the below instructions
* Follow the instructions provided to sign in:
   * Start a web browser and go to https://aka.ms/devicelogin - we strongly suggest you use your web browser's "private mode".
   * Enter the security code provided in the command prompt
   * Consent to using ChannelSurfCli
   * Enter your O365 credentials.  
   * Return to your command prompt 

However, i do not see a way to complete the following

* Select the target Microsoft Team you want to create or re-create your channels into.  You can also choose to create a new Microsoft Team.
* Go back to the Microsoft Team app and explore the channels you added!

**Comment by essgit** [comment]
This is the only section you are supposed to edit:

Update appsettings.json in the ChannelSurfCli folder. Within the section called "AzureAd", update the fields with your tenant name (TenantId), Application ID (ClientId), and Redirect URI (AadRedirectUri). You can leave the value for AadInstance as-is.

**Comment by maardappel** [comment]
I was having this issue as well. What solved it for me was making a change to the API permissions. I had it set for User.Read instead of User.Read.All. After changing over, it was able to run further.
